version: '3.4'

networks:
  default:
    external:
      name: docker-shared-network

volumes:
  mongo:
    driver: local

services:
  front:
    image: registry.mbtl.life/sb.frontend:prod
    container_name: front
    restart: unless-stopped

  api:
    image: registry.mbtl.life/sb.api:prod
    container_name: api
    restart: unless-stopped
    environment:
      - Authentication__Google__ClientId=<google_client_id>
      - Authentication__Jwt__Audience=https://stickerboard.eu
      - Authentication__Jwt__Issuer=https://stickerboard.eu
      - Authentication__Jwt__EmailEncryptionSecret=<some_secret>
      - Authentication__Jwt__Secret=<some_secret>
      - mongo__ConnectionString=mongodb://mongo:27017
      - mongo__Database=sb-prod
      - mongo__seed=false

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    hostname: mongo
    volumes:
      - mongo:/data/db # DB data
    command: ["--replSet", "rs0"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo  --quiet) -eq 1
      interval: 10s
      start_period: 30s
