# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: "Publish"
#   inputs:
#     command: 'publish'
#     publishWebProjects: false
#     projects: 'SB.Web/*.csproj'
#     configuration: $(buildConfiguration)'
#     arguments: '--output $(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   displayName: "Upload Artifacts"
#   inputs:
#     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'SB.Web'



    
    # - task: DockerInstaller@0
    #   inputs:
    #     dockerVersion: '17.09.0-ce'
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '**/api/Dockerfile.prod'
    