trigger:
  branches:
    include:
      - master

variables:
  buildConfiguration: 'Release'
  branchName: $(System.PullRequest.SourceBranch)
  buildName: '$(branchName)-$(Build.BuildId)'

name: $(System.PullRequest.SourceBranch)-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Login to Azure Container Registry
    inputs:
      command: login
      containerRegistry: azureContainerRegistryStickerBoard

  - task: Docker@2
    inputs:
      containerRegistry: 'azureContainerRegistryStickerBoard'
      repository: 'sb.api'
      command: 'buildAndPush'
      Dockerfile: 'api/Dockerfile.prod'
      tags: |
        $(buildName)
        $(branchName)