trigger:
- master

variables:
  buildConfiguration: 'Release'
  branchName: $(System.PullRequest.SourceBranch)
  buildName: '$(branchName)-$(Build.BuildId)'

name: $(System.PullRequest.SourceBranch)-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        branchFullName=$(git describe --contains --all HEAD)
        echo "##vso[task.setvariable variable=branchFullName;isOutput=true]$branchFullName"
    name: branchName
  
  - script: echo $(branchName.branchFullName)
    name: echovar

  - task: Docker@2
    displayName: Login to Azure Container Registry
    inputs:
      containerRegistry: 'Nazwa.pl docker registry'
      command: 'login'

  - task: Docker@2
    inputs:
      containerRegistry: 'Nazwa.pl docker registry'
      repository: 'sb.api'
      command: 'buildAndPush'
      Dockerfile: 'api/Dockerfile.prod'
      tags: |
        $(buildName)
        $(branchName)
        