trigger:
- master

variables:
  buildConfiguration: 'Release'
  branchName: $(System.PullRequest.SourceBranch)
  buildName: '$(branchName)-$(Build.BuildId)'

name: $(System.PullRequest.SourceBranch)-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        BRANCH_NAME=$(echo "$(System.PullRequest.TargetBranch)" | awk -F/ '{print $NF}')
        echo "##vso[task.setvariable variable=PullRequest_Target_Branch;]$BRANCH_NAME"
  
  - script: echo $(PullRequest_Target_Branch)
    name: echovar

  - task: Docker@2
    displayName: Login to Azure Container Registry
    inputs:
      containerRegistry: 'Nazwa.pl docker registry'
      command: 'login'

  - task: Docker@2
    inputs:
      containerRegistry: 'Nazwa.pl docker registry'
      repository: 'sb.api'
      command: 'buildAndPush'
      Dockerfile: 'api/Dockerfile.prod'
      tags: |
        $(buildName)
        $(branchName)
        