trigger:
- master

variables:
  buildConfiguration: 'Release'
  branchName: $(System.PullRequest.SourceBranch)
  buildName: '$(branchName)-$(Build.BuildId)'

name: $(System.PullRequest.SourceBranch)-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Login to docker registry
    inputs:
      containerRegistry: 'Nazwa.pl docker registry'
      command: 'login'

  - task: Docker@2
    inputs:
      containerRegistry: 'Nazwa.pl docker registry'
      repository: 'sb.api'
      command: 'buildAndPush'
      Dockerfile: 'api/Dockerfile.prod'
      tags: |
        $(buildName)
        $(branchName)
        