FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy everything else and build
COPY . ./
RUN sh SB.Web/scripts/publish.sh

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/SB.Web/out .
ENTRYPOINT ["dotnet", "SB.Web.dll"]